#!/usr/bin/env python3
"""Build a static daily ML Pulse digest page. No LLM key required.

Reads the public Hugging Face Daily Papers + newest arXiv feeds through the
app's own ``trends.refresh_pulse`` (falls back to rule-based items when no
Groq key is present), scores each item against a generalist-MLE stack, and
writes a self-contained HTML page.

Usage:
    MLE_DATA_DIR=/tmp/pulse-digest python scripts/build_pulse_digest.py \
        --out docs/pulse/index.html
"""

from __future__ import annotations

import argparse
import html
import os
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from trends import (  # noqa: E402
    CONCEPTS,
    draft_decision_memo,
    load_pulse,
    refresh_pulse,
    score_against_stack,
)
from database import get_db  # noqa: E402

# A broad default stack so the public digest is useful without a personal one.
DEFAULT_STACK = [
    "Transformers",
    "RL post-training",
    "Retrieval-augmented generation",
    "Agents",
    "LoRA / adapters",
    "Quantization",
    "Long context",
    "Evaluation / benchmarks",
]

VERDICT_STYLE = {
    "adopt": ("Adopt", "#3fb950"),
    "prototype": ("Prototype", "#d4a574"),
    "watch": ("Watch", "#79c0ff"),
    "skip": ("Skip", "#8b949e"),
}

CONCEPT_BLURBS = {name: blurb for name, blurb, _keys in CONCEPTS}


def _card(item, stack) -> str:
    fit = score_against_stack(item, stack)
    memo = draft_decision_memo(item, fit, stack)
    label, color = VERDICT_STYLE.get(memo.verdict, (memo.verdict.title(), "#8b949e"))
    title = html.escape(item.paper_title or item.topic or "Untitled")
    topic = html.escape(item.topic or "")
    concept = html.escape(item.concept or "")
    blurb = html.escape(item.concept_blurb or CONCEPT_BLURBS.get(item.concept, ""))
    why = html.escape(item.why or "")
    abstract = html.escape((item.abstract or "")[:600])
    constraint = html.escape(memo.constraint or "")
    so_what = html.escape(memo.so_what or "")
    url = html.escape(
        item.paper_url or (f"https://arxiv.org/abs/{item.paper_id}" if item.paper_id else "")
    )
    link = f'<a href="{url}">Paper &rarr;</a>' if url else ""
    return f"""
    <article class="card">
      <div class="card-top"><span class="verdict" style="border-color:{color};color:{color}">{label}</span>
      <span class="fit">{html.escape(fit.label)} · {fit.score}</span></div>
      <h3>{title}</h3>
      {f'<p class="topic">{topic}</p>' if topic and topic != title else ''}
      <p class="concept"><strong>{concept}</strong> — {blurb}</p>
      {f'<p class="why">{why}</p>' if why else ''}
      {f'<p class="abstract">{abstract}…</p>' if abstract else ''}
      <p class="constraint">⚠ {constraint}</p>
      <p class="sowhat">{so_what}</p>
      <div class="links">{link}</div>
    </article>"""


def build_html(items, stack, errors, fetched_at: str) -> str:
    cards = "\n".join(_card(i, stack) for i in items) or (
        "<p>No recent papers matched the pulse window. Check back tomorrow.</p>"
    )
    err_html = ""
    if errors:
        lis = "".join(f"<li>{html.escape(e)}</li>" for e in errors)
        err_html = f"<details class='errors'><summary>Feed notes ({len(errors)})</summary><ul>{lis}</ul></details>"
    today = date.today().isoformat()
    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>ML Pulse — {today}</title>
<style>
body{{font-family:system-ui,-apple-system,sans-serif;max-width:900px;margin:0 auto;padding:24px;color:#e6edf3;background:#0d1117}}
a{{color:#79c0ff}} h1{{letter-spacing:-0.02em}} .muted{{color:#8b949e}}
.card{{border:1px solid #30363d;border-radius:12px;padding:18px;margin:16px 0;background:#161b22}}
.card-top{{display:flex;justify-content:space-between;align-items:center;margin-bottom:8px}}
.verdict{{border:1px solid;border-radius:999px;padding:2px 12px;font-size:12px;font-weight:600}}
.fit{{color:#8b949e;font-size:13px}} .concept{{color:#d4a574}} .why{{font-style:italic}}
.abstract{{color:#8b949e;font-size:14px}} .constraint{{font-size:14px}}
.sowhat{{font-size:14px}} .errors{{margin:16px 0;color:#8b949e;font-size:13px}}
footer{{margin-top:32px;color:#8b949e;font-size:13px}}
</style></head><body>
<h1>ML Pulse</h1>
<p class="muted">What moved in ML/AI on {today} — trending papers mapped to concepts,
ranked for a generalist MLE stack, with a decision memo each. Updated daily.
Fetched {html.escape(fetched_at or '')}.</p>
{err_html}
{cards}
<footer>Generated by <a href="https://github.com/messishivi/mle-professor-app">MLE Professor</a>
· verdicts are rule-based drafts, not financial/production advice.</footer>
</body></html>
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True, help="Output HTML path")
    ap.add_argument("--stack", nargs="*", default=DEFAULT_STACK,
                    help="Concept names to score against")
    args = ap.parse_args()

    # Explicit store path: works whether or not the MLE_DATA_DIR patch
    # (patches/mle-data-dir.patch) is applied to database.py.
    data_dir = Path(os.environ.get("MLE_DATA_DIR", "/tmp/pulse-digest")).expanduser()
    store = get_db(data_dir / "mle_knowledge.db")
    snapshot = refresh_pulse(store)
    pulse = load_pulse(store)
    items = pulse.items if pulse else []
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build_html(items, args.stack, snapshot.errors, snapshot.fetched_at),
                   encoding="utf-8")
    print(f"digest: {len(items)} items -> {out} (errors: {len(snapshot.errors)})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
